// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AccountAll() {
  return window['go']['game']['Api']['AccountAll']();
}

export function AccountCreate(arg1) {
  return window['go']['game']['Api']['AccountCreate'](arg1);
}

export function ActiveAccountGet() {
  return window['go']['game']['Api']['ActiveAccountGet']();
}

export function MapInfoSet(arg1, arg2) {
  return window['go']['game']['Api']['MapInfoSet'](arg1, arg2);
}

export function PlayerGet() {
  return window['go']['game']['Api']['PlayerGet']();
}

export function PlayerLoad(arg1, arg2) {
  return window['go']['game']['Api']['PlayerLoad'](arg1, arg2);
}

export function PlayerSetMotion(arg1) {
  return window['go']['game']['Api']['PlayerSetMotion'](arg1);
}

export function SettingsGet(arg1) {
  return window['go']['game']['Api']['SettingsGet'](arg1);
}

export function SettingsSet(arg1) {
  return window['go']['game']['Api']['SettingsSet'](arg1);
}
