// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {game} from '../models';

export function AccountAll():Promise<Array<game.Account>>;

export function AccountCreate(arg1:string):Promise<game.Account>;

export function ActiveAccountGet():Promise<game.Account>;

export function MapInfoSet(arg1:Array<number>,arg2:string):Promise<game.MapInfo>;

export function PlayerGet():Promise<game.Player>;

export function PlayerLoad(arg1:string,arg2:string):Promise<game.Player>;

export function PlayerSetMotion(arg1:game.Point):Promise<void>;

export function SettingsGet(arg1:game.SettingsResolution):Promise<game.Settings>;

export function SettingsSet(arg1:game.SettingsResolution):Promise<game.Settings>;
